# Generated by Django 6.0 on 2025-12-26 11:00

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='artists/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to=app.models.artist_image_path)),
                ('views', models.IntegerField(blank=True, default=0, null=True)),
                ('parse_tracks', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('yt_id', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='genres/')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=app.models.album_cover_path)),
                ('track_count', models.IntegerField(blank=True, default=0, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('single', 'Single'), ('album', 'Album'), ('ep', 'EP')], default='album', max_length=10)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('yt_id', models.CharField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='app.artist')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='genres',
            field=models.ManyToManyField(to='app.genre'),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.IntegerField(blank=True, default=0)),
                ('duration', models.IntegerField(blank=True, default=0, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=app.models.track_file_path)),
                ('yt_id', models.CharField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='app.album')),
                ('featured_artists', models.ManyToManyField(to='app.artist')),
            ],
        ),
    ]
