# Generated by Django 6.0 on 2025-12-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='icon',
            new_name='thumbnail',
        ),
    ]
