# Generated by Django 6.0 on 2025-12-25 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='artist',
            name='yt_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
