# Generated by Django 6.0 on 2025-12-29 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_icon_genre_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='listens',
            field=models.IntegerField(default=0),
        ),
    ]
