# Generated by Django 6.0 on 2025-12-25 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_artist_youtube_link_artist_yt_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='artists/'),
        ),
        migrations.AddField(
            model_name='artist',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
