# Generated by Django 6.0 on 2025-12-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_album_release_date_artist_banner_artist_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(related_name='albums', to='app.artist'),
        ),
    ]
