# Generated by Django 6.0 on 2026-01-18 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_emailverificationtoken_passwordresettoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_new_releases', models.BooleanField(default=True, help_text='New releases from followed artists')),
                ('email_recommendations', models.BooleanField(default=True, help_text='Weekly music recommendations')),
                ('app_playlist_updates', models.BooleanField(default=True, help_text='When playlists you follow are updated')),
                ('app_friend_activity', models.BooleanField(default=False, help_text='When friends share music or playlists')),
                ('app_concert_alerts', models.BooleanField(default=False, help_text='Concert announcements near you')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crossfade_duration', models.IntegerField(default=0, help_text='Crossfade duration in seconds (0-12)')),
                ('gapless_playback', models.BooleanField(default=True, help_text='Enable gapless playback between tracks')),
                ('private_account', models.BooleanField(default=False, help_text='Only approved followers can see your activity')),
                ('show_activity_status', models.BooleanField(default=True, help_text="Let others see when you're listening")),
                ('share_listening_history', models.BooleanField(default=True, help_text='Used for personalized recommendations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Preferences',
                'verbose_name_plural': 'User Preferences',
            },
        ),
        migrations.CreateModel(
            name='ListeningHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('play_duration', models.IntegerField(default=0, help_text='Duration played in seconds')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_history', to='app.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Listening History',
                'verbose_name_plural': 'Listening History',
                'ordering': ['-played_at'],
                'indexes': [models.Index(fields=['user', '-played_at'], name='app_listeni_user_id_a025c5_idx'), models.Index(fields=['track', '-played_at'], name='app_listeni_track_i_2d8900_idx')],
            },
        ),
    ]
