# Generated by Django 6.0 on 2025-12-25 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_name_album_title_rename_name_track_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='track_number',
            new_name='track_count',
        ),
        migrations.AddField(
            model_name='track',
            name='duration',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='app.album'),
        ),
    ]
