# Generated by Django 6.0 on 2025-12-26 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_track_number_album_track_count_track_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tracks/'),
        ),
    ]
