# Generated by Django 4.2.27 on 2026-01-19 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listeninghistory',
            options={'ordering': ['-played_at']},
        ),
        migrations.CreateModel(
            name='SavedAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='app.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_albums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Album',
                'verbose_name_plural': 'Saved Albums',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='app_savedal_user_id_c48209_idx')],
                'unique_together': {('user', 'album')},
            },
        ),
        migrations.CreateModel(
            name='FollowedArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by_users', to='app.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_artists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Followed Artist',
                'verbose_name_plural': 'Followed Artists',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='app_followe_user_id_642879_idx')],
                'unique_together': {('user', 'artist')},
            },
        ),
    ]
