# Generated by Django 6.0 on 2025-12-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_track_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='type',
            field=models.CharField(choices=[('single', 'Single'), ('album', 'Album'), ('ep', 'EP')], default='album', max_length=10),
        ),
    ]
