# Generated by Django 6.0 on 2025-12-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_album_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='parse_tracks',
            field=models.BooleanField(default=True),
        ),
    ]
