# Generated by Django 6.0.2 on 2026-02-21 17:17

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_favoritetrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=app.models.track_file_path),
        ),
    ]
