# Generated by Django 6.0.2 on 2026-02-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_track_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='type',
            new_name='album_type',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='file',
            new_name='track_file',
        ),
    ]
